# Frontend Project Auto-Labeler Configuration

frontend:
  - "src/**"
  - "public/**"
  - "app/**"
  - "pages/**"

docs:
  - "docs/**"
  - "*.md"
  - "README*"

infra:
  - ".github/**"
  - "Dockerfile"
  - "docker-compose*.yml"
  - ".dockerignore"
  - "nginx/**"
  - "nginx.conf"

config:
  - "*.config.js"
  - "*.config.ts"
  - "*.config.mjs"
  - "vite.config.*"
  - "next.config.*"
  - "nuxt.config.*"
  - "webpack.config.*"
  - "rollup.config.*"
  - "tsconfig*.json"
  - "jsconfig*.json"
  - ".eslintrc*"
  - ".prettierrc*"
  - "tailwind.config.*"
  - "postcss.config.*"

# Frontend Layer Labels
layer:components:
  - "src/components/**"
  - "components/**"
  - "app/components/**"

layer:pages:
  - "src/pages/**"
  - "pages/**"
  - "app/**/page.*"
  - "src/views/**"
  - "views/**"

layer:hooks:
  - "src/hooks/**"
  - "hooks/**"
  - "src/composables/**"
  - "composables/**"

layer:utils:
  - "src/utils/**"
  - "utils/**"
  - "src/lib/**"
  - "lib/**"
  - "src/helpers/**"

layer:store:
  - "src/store/**"
  - "src/stores/**"
  - "store/**"
  - "stores/**"
  - "src/redux/**"
  - "src/recoil/**"
  - "src/zustand/**"

layer:api:
  - "src/api/**"
  - "src/services/**"
  - "api/**"
  - "services/**"

layer:styles:
  - "src/styles/**"
  - "styles/**"
  - "**/*.css"
  - "**/*.scss"
  - "**/*.sass"
  - "**/*.less"

layer:types:
  - "src/types/**"
  - "types/**"
  - "**/*.d.ts"

layer:assets:
  - "src/assets/**"
  - "assets/**"
  - "public/**"

layer:test:
  - "**/*.test.*"
  - "**/*.spec.*"
  - "__tests__/**"
  - "tests/**"
  - "test/**"
  - "cypress/**"
  - "e2e/**"

dependencies:
  - "package.json"
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
